### PR TITLE
feat: user login

### PR DESCRIPTION
**Pull request by chuelgi**
*backend route to login

### CODE REVIEW

**Comment by jaredsina** [comment]
Will we be providing JWT Token as a response to a login?

**Comment by chuelgi** [comment]
> Will we be providing JWT Token as a response to a login?

Yes. When they finish setting up JWT I will have to update the user functions.

**Comment by jaredsina** [comment]
We have finished the JWT Token config on the backend. You should be able to generate them and provide them in the response. Can be seen in this PR: https://github.com/chingu-voyages/v49-tier3-team-29/pull/19

**Comment by chuelgi** [comment]
> We have finished the JWT Token config on the backend. You should be able to generate them and provide them in the response. Can be seen in this PR: #19

I just looked at the Trello board. 2 others will handle the token and I will join them if they would like. For now its best to merge this branch into dev so it can be worked on. This branch was created and completed before JWT was added.

**Review by jaredsina — APPROVED** [review]

**Pull request merged**
