### PR TITLE
Feat/get delete backend route list

### PR DESCRIPTION
**Pull request by bank1e**
Hi Team,
This has been branched from Alex's PR#42 as I and Alex discussed today in Discord voice chat.

Since list function is ongoing task by other team members, I am not sure if I missed any routes. Please feel free to comment if there is a need for revision:

So far, I created:

-   deleteList
-   getAllLists
-   getListById
-   getListByUserId

image

### CODE REVIEW

**Comment by alexh205** [comment]
@bank1e I don't think we would need the following routes: 
- 'getAllLists'
- 'getListById'

Since each user will only have 'one' associated List. We can also update the 'deleteList' route to 'removeListBook'.

**Comment by bank1e** [comment]
**Purpose:**
- Create a route to request list by user ID.
- Create a route to request remove book from list.

**Changes:**
- Added route to get list by user ID
- Added route to remove one book from an existing list by a combination of list ID + book ID
- Added removeListBook function
- Added getListByUserId function

**How to review:**
(1) Add a book in user's list. Send GET request via the getListByUserId route to check if the book is inserted in the user's list.
image
 
(2) The book has been removed via removeListBook route by the combination of list ID + book ID.
image

(3) Make sure the book is removed from the user's list.
image

**Comment by bank1e** [comment]
> @bank1e I don't think we would need the following routes:
> 
> * 'getAllLists'
> * 'getListById'
> 
> Since each user will only have 'one' associated List. We can also update the 'deleteList' route to 'removeListBook'.

@alexh205 Thank you for providing a detailed feedback! I have revised the codes as per your advice. Do you mind reviewing the revised version?

**Comment by alexh205** [comment]
@bank1e The functions look great! I have made some updates to the code. Here is a breakdown of the updates:

- Updated the 'removeListBook' route from a 'Delete' method to a 'patch' method, since we not really deleting the list object but rather updating a property 'books' of the list object. removed the 'bookId' from the pathway and into the 'req.body' for a shorter route URI. 
- Updated the 'removeListBook' controller to check for errors first, update/remove bookId, then populate the book object into the 'books' property before returning it back as a response object. 
- Updated the 'getListByUserId' controller to also populate the book object into the 'books' property before returning it back as a response object. 

I have pushed my updates to the branch. Please take and do let me know if you have questions, or comments about the code.

https://github.com/chingu-voyages/v49-tier3-team-29/assets/95322089/c571a103-2298-4fc5-907c-36cb3e87bbce

**Comment by bank1e** [comment]
@alexh205 Thank you for updating the getListByUserId and the removeListBook. I reviewed the updated version at my local environment and learned how it works! I do not have to comment on the updates. Please go ahead for approving the PR.

**Comment by alexh205** [comment]
@bank1e Thank you for your feedback!

**Review by alexh205 — APPROVED** [review]
This PR is now approved!

**Pull request merged**
