### PR TITLE
Feat/add image url to book model

### PR DESCRIPTION
**Pull request by bank1e**
**Purpose:**
- Add an image static URL for book cover to _Books_ model.

Change(s):
- Added _imageUrl_ to Books model.

How to review:
- Just check if _imageUrl_ exists in Books model.
image

### CODE REVIEW

**Comment by jaredsina** [comment]
Changed main to dev for this PR.

**Comment by bank1e** [comment]
Thank you for the correction. I did not pay attention to that. I will make sure PR is pointed to main from now on!

**Comment by jaredsina** [comment]
Can you help me understand the image url a bit more.

- Will the seeders provide book cover imageUrl to the books we create?  
- Can you give me an example imageURL that might be uploaded with a Book Model

**Comment by bank1e** [comment]
Will the seeders provide book cover imageUrl to the books we create?
Bia: Yes it does. Seeders will have an imageUrl for the book cover. 
Can you give me an example imageURL that might be uploaded with a Book Model
Bia: For example, Camino Ghosts: A Novel has the following static image url:
https://m.media-amazon.com/images/I/51o0FM+NzTL._SY445_SX342_.jpg

**Review by jaredsina — APPROVED** [review]

**Pull request merged**
