### PR TITLE
Feat/list reducer

### PR DESCRIPTION
**Pull request by bank1e**
Hi Alex,
I followed bookSlice.js to draft listSlice.js but I am not sure how to test it. Would you mind briefly reviewing listSlice.js, store.js and baseUrl.js? Thank you.

### CODE REVIEW

**Comment by alexh205** [comment]
@bank1e It is difficult to test the slicer function without being able to pull data from the backend, but we can perform a sudo test by pulling the book data into the 'list slicer' function as such: 

- modify the book fetch function on the Hero component of the landing Page: 

CleanShot 2024-06-05 at 18 01 12

- Update the list's 'Create Thunk' function [within the listSlice module] to call the 'bookBaseUrl' instead of 'listBaseUrl': 

CleanShot 2024-06-05 at 18 02 37

- As you can see we can pass the books object into the list store: 

CleanShot 2024-06-05 at 17 59 01


Here are other minor updates:

- List reducer naming convention for alignment purposes 
image

- listSlice function- removal of extra action.types 
image

- baseUrl module update:
image

**Comment by bank1e** [comment]
@alexh205 Thank you very much for the detailed advice and correction! Successfully tested the listSlice.js. I will post this PR soon.

**Comment by bank1e** [comment]
**Purpose:**
- Create list reducer

**Change(s):**
1.  Created listSlice.js to fetch list
2. Added listReducer in store.js
3. Added listBaseURL in baseUrl.js

**How to review:**
Modified Hero component in landing page to get data from book collection into list reducer in landing page. Upon fetching data from book, list reducer is triggered and book collection is fetched in the list store: Video_2024-06-06_162541

**Review by alexh205 — APPROVED** [review]
@bank1e, Thank you for making the appropriate updates. I have no further comments.

**Pull request merged**
